# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-10'

steps:
- task: BatchScript@1
  displayName: "Find 3^4 using windows batch file because for some reason we really, really hate ourselves"
  inputs:
    filename: 'power.bat'
    arguments: '3 4'
